engines:
  tslint:
    enabled: true
    channel: beta
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - typescript
      - python
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "app/**/*.ts"
  - "src/app/**/*.ts"
  - "**.js"
  - "**.jsx"
exclude_paths:
  - config/**
  - dist/**
  - vendor/**
  - node_modules/**
  - bower_components/**
  - tmp/**
  - assets/**
  - karma.conf.js
