---
engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
  - config/**
  - dist/**
  - vendor/**
  - node_modules/**
  - bower_components/**
  - tmp/**
  - assets/**
